class AdminManageSeedDefaults {
  static const valuesByCategory = {
    'meal_categories': [
      'Breakfast',
      'Lunch',
      'Dinner',
      'Snack',
      'Dessert',
      'Beverage',
    ],
    'ingredient_categories': [
      'Dairy',
      'Meat',
      'Poultry',
      'Seafood',
      'Eggs',
      'Vegetables',
      'Fruits',
      'Grains',
      'Legumes',
      'Nuts & Seeds',
      'Herbs & Spices',
      'Oils & Fats',
      'Sauces & Condiments',
      'Sweeteners',
      'Beverages',
      'Processed Foods',
    ],
    'recipe_categories': [
      'Italian',
      'Chinese',
      'Malay',
      'Indian',
      'Japanese',
      'Korean',
      'Thai',
      'Western',
      'Mexican',
      'Mediterranean',
      'Dessert',
      'Healthy',
      'Quick & Easy',
      'Vegetarian',
    ],
    'meal_preferences': [
      'No specific diet',
      'Classic',
      'Low Carb',
      'Keto',
      'Flexitarian',
      'Paleo',
      'Vegetarian',
      'Pescetarian',
      'Vegan',
      'Halal',
    ],
    'allergies': [
      'None',
      'Milk',
      'Cheese',
      'Egg',
      'Peanut',
      'Tree Nut',
      'Soy',
      'Sesame',
      'Wheat',
      'Gluten',
      'Fish',
      'Shellfish',
      'Shrimp',
      'Crab',
      'Dairy',
      'Seafood',
    ],
    'dislikes': [
      'None',
      'Avocado',
      'Beets',
      'Bell Peppers',
      'Brussels Sprouts',
      'Cauliflower',
      'Eggplant',
      'Mushrooms',
      'Olives',
      'Quinoa',
      'Tofu',
      'Turnips',
      'Onion',
      'Garlic',
      'Cilantro',
      'Spicy Food',
      'Bitter Melon',
    ],
  };
}
