// Implements repository operations for help center.

import 'dart:io';
import 'package:dartz/dartz.dart';
import '../../../../core/error/failures.dart';
import '../../domain/entities/help_center_issue.dart';
import '../../domain/repositories/help_center_repository.dart';
import '../datasources/help_center_remote_datasource.dart';
import '../models/help_center_issue_model.dart';

/// Defines behavior for help center repository impl.
/// Implements the HelpCenterRepository interface using remote data source.
class HelpCenterRepositoryImpl implements HelpCenterRepository {
  /// Remote data source for help center operations.
  final HelpCenterRemoteDataSource remoteDataSource;

  /// Creates a help center repository impl instance.
  HelpCenterRepositoryImpl({required this.remoteDataSource});

  /// Loads data for the get user issues operation.
  @override
  Future<Either<Failure, List<HelpCenterIssue>>> getUserIssues(
      String uid,
      ) async {
    try {
      // Runs the guarded operation that can throw.
      final snapshot = await remoteDataSource.getUserIssues(uid);

      // Map Firestore documents to domain entities and sort by timestamp descending.
      final issues =
      snapshot.docs
          .map((doc) => HelpCenterIssueModel.fromFirestore(doc))
          .toList()
        ..sort((a, b) => b.timestamp.compareTo(a.timestamp));

      return Right(issues);
    } catch (e) {
      // Map any exception to a server failure.
      return Left(ServerFailure(message: e.toString()));
    }
  }

  /// Loads data for the get all issues operation.
  @override
  Future<Either<Failure, List<HelpCenterIssue>>> getAllIssues() async {
    try {
      // Runs the guarded operation that can throw.
      final snapshot = await remoteDataSource.getAllIssues();

      // Map Firestore documents to domain entities.
      final issues = snapshot.docs
          .map((doc) => HelpCenterIssueModel.fromFirestore(doc))
          .toList();

      return Right(issues);
    } catch (e) {
      // Map any exception to a server failure.
      return Left(ServerFailure(message: e.toString()));
    }
  }

  /// Runs the submit issue operation.
  @override
  Future<Either<Failure, void>> submitIssue({
    required String uid,
    required String message,
    File? imageFile,
  }) async {
    try {
      // Runs the guarded operation that can throw.
      String? imageUrl;

      // Upload image if provided.
      if (imageFile != null) {
        imageUrl = await remoteDataSource.uploadIssueImage(imageFile);
      }

      // Create issue model.
      final issue = HelpCenterIssueModel(
        id: '', // Will be auto-generated by Firestore
        uid: uid,
        message: message,
        imageUrl: imageUrl,
        replied: false,
        timestamp: DateTime.now(),
      );

      // Save to remote data source.
      await remoteDataSource.addIssue(issue.toJson());
      return const Right(null);
    } catch (e) {
      // Map any exception to a server failure.
      return Left(ServerFailure(message: e.toString()));
    }
  }

  /// Handles the mark issue as replied operation.
  @override
  Future<Either<Failure, void>> markIssueAsReplied(String issueId) async {
    try {
      // Runs the guarded operation that can throw.
      await remoteDataSource.updateIssueStatus(issueId, true);
      return const Right(null);
    } catch (e) {
      // Map any exception to a server failure.
      return Left(ServerFailure(message: e.toString()));
    }
  }

  /// Replies to an issue.
  @override
  Future<Either<Failure, void>> replyToIssue({
    required String issueId,
    required String userUid,
    required String reply,
  }) async {
    try {
      await remoteDataSource.replyToIssue(
        issueId: issueId,
        userUid: userUid,
        reply: reply,
      );
      return const Right(null);
    } catch (e) {
      // Map any exception to a server failure.
      return Left(ServerFailure(message: e.toString()));
    }
  }

  /// Runs the upload issue image operation.
  @override
  Future<Either<Failure, String>> uploadIssueImage(File imageFile) async {
    try {
      // Runs the guarded operation that can throw.
      final imageUrl = await remoteDataSource.uploadIssueImage(imageFile);
      return Right(imageUrl);
    } catch (e) {
      // Map any exception to a server failure.
      return Left(ServerFailure(message: e.toString()));
    }
  }

  /// Loads data for the get user email operation.
  @override
  Future<Either<Failure, String>> getUserEmail(String uid) async {
    try {
      // Runs the guarded operation that can throw.
      final userDoc = await remoteDataSource.getUserData(uid);

      // Extract email if user exists.
      if (userDoc.exists) {
        final data = userDoc.data() as Map<String, dynamic>?;
        final email = data?['email'] as String?;
        return Right(email ?? '');
      }

      return Right('');
    } catch (e) {
      // Map any exception to a server failure.
      return Left(ServerFailure(message: e.toString()));
    }
  }
}