import 'dart:io';
import 'package:dartz/dartz.dart';
import '../../../../core/error/failures.dart';
import '../../domain/entities/help_center_issue.dart';
import '../../domain/repositories/help_center_repository.dart';
import '../datasources/help_center_remote_datasource.dart';
import '../models/help_center_issue_model.dart';

class HelpCenterRepositoryImpl implements HelpCenterRepository {
  final HelpCenterRemoteDataSource remoteDataSource;

  HelpCenterRepositoryImpl({required this.remoteDataSource});

  @override
  Future<Either<Failure, List<HelpCenterIssue>>> getUserIssues(String uid) async {
    try {
      final snapshot = await remoteDataSource.getUserIssues(uid);
      final issues = snapshot.docs
          .map((doc) => HelpCenterIssueModel.fromFirestore(doc))
          .toList();
      return Right(issues);
    } catch (e) {
      return Left(ServerFailure(message: e.toString()));
    }
  }

  @override
  Future<Either<Failure, List<HelpCenterIssue>>> getAllIssues() async {
    try {
      final snapshot = await remoteDataSource.getAllIssues();
      final issues = snapshot.docs
          .map((doc) => HelpCenterIssueModel.fromFirestore(doc))
          .toList();
      return Right(issues);
    } catch (e) {
      return Left(ServerFailure(message: e.toString()));
    }
  }

  @override
  Future<Either<Failure, void>> submitIssue({
    required String uid,
    required String message,
    File? imageFile,
  }) async {
    try {
      String? imageUrl;
      if (imageFile != null) {
        imageUrl = await remoteDataSource.uploadIssueImage(imageFile);
      }

      final issue = HelpCenterIssueModel(
        id: '', // Will be auto-generated by Firestore
        uid: uid,
        message: message,
        imageUrl: imageUrl,
        replied: false,
        timestamp: DateTime.now(),
      );

      await remoteDataSource.addIssue(issue.toJson());
      return const Right(null);
    } catch (e) {
      return Left(ServerFailure(message: e.toString()));
    }
  }

  @override
  Future<Either<Failure, void>> markIssueAsReplied(String issueId) async {
    try {
      await remoteDataSource.updateIssueStatus(issueId, true);
      return const Right(null);
    } catch (e) {
      return Left(ServerFailure(message: e.toString()));
    }
  }

  @override
  Future<Either<Failure, String>> uploadIssueImage(File imageFile) async {
    try {
      final imageUrl = await remoteDataSource.uploadIssueImage(imageFile);
      return Right(imageUrl);
    } catch (e) {
      return Left(ServerFailure(message: e.toString()));
    }
  }

  @override
  Future<Either<Failure, String>> getUserEmail(String uid) async {
    try {
      final userDoc = await remoteDataSource.getUserData(uid);
      if (userDoc.exists) {
        final data = userDoc.data() as Map<String, dynamic>?;
        final email = data?['email'] as String?;
        return Right(email ?? '');
      }
      return Right('');
    } catch (e) {
      return Left(ServerFailure(message: e.toString()));
    }
  }
}