import 'meal_calorie_guidance.dart';

/// Represents the complete plan for adding AI-generated meals.
/// Contains all data needed for the AI meal planning interface.
class AddMealAiPlan {
  /// The date for which meals are being planned.
  final DateTime planningDate;

  /// Type of meal (e.g., breakfast, lunch, dinner).
  final String mealType;

  /// Weather information for the planning date.
  final AddMealWeather weather;

  /// User's dietary preferences snapshot.
  final AddMealPreferenceSnapshot preferences;

  /// List of ingredients to include in meal suggestions.
  final List<String> ingredientsToInclude;

  /// List of ingredients to avoid in meal suggestions.
  final List<String> ingredientsToAvoid;

  /// User's preferred dish categories.
  final List<String> dishPreferences;

  /// Top matching recipes from the database.
  final List<AddMealAiRecipe> topMatches;

  /// AI-generated meal ideas.
  final List<AddMealAiRecipe> aiIdeas;

  /// Creates a new AI meal plan instance.
  const AddMealAiPlan({
    required this.planningDate,
    required this.mealType,
    required this.weather,
    required this.preferences,
    required this.ingredientsToInclude,
    required this.ingredientsToAvoid,
    required this.dishPreferences,
    required this.topMatches,
    required this.aiIdeas,
  });
}

/// Request object for generating AI meal ideas.
/// Contains all parameters for the AI generation process.
class AddMealAiGenerationRequest {
  /// The date for which meals are being generated.
  final DateTime planningDate;

  /// Type of meal to generate.
  final String mealType;

  /// Weather information for the planning date.
  final AddMealWeather weather;

  /// User's dietary preferences.
  final AddMealPreferenceSnapshot preferences;

  /// Ingredients to include in generated meals.
  final List<String> ingredientsToInclude;

  /// Ingredients to avoid in generated meals.
  final List<String> ingredientsToAvoid;

  /// Dish types to include in generation.
  final List<String> dishIncludes;

  /// Dish types to avoid in generation.
  final List<String> dishAvoids;

  /// Maximum cooking time in minutes.
  final int cookingTime;

  /// Difficulty level as a numeric value.
  final int difficultyLevel;

  /// Difficulty level as a string label.
  final String difficulty;

  /// Number of servings for the meal.
  final int servingCount;

  /// Serving size description.
  final String servingSize;

  /// Calorie budget for the selected planning day.
  final MealCalorieBudget calorieBudget;

  /// Existing planned meal names to avoid repeating.
  final List<String> existingMealNames;

  /// Creates a new AI generation request.
  const AddMealAiGenerationRequest({
    required this.planningDate,
    required this.mealType,
    required this.weather,
    required this.preferences,
    required this.ingredientsToInclude,
    required this.ingredientsToAvoid,
    required this.dishIncludes,
    required this.dishAvoids,
    required this.cookingTime,
    required this.difficultyLevel,
    required this.difficulty,
    required this.servingCount,
    required this.servingSize,
    this.calorieBudget = const MealCalorieBudget.empty(),
    this.existingMealNames = const [],
  });
}

/// Represents weather information for meal planning.
/// Contains temperature, condition, and summary description.
class AddMealWeather {
  /// Temperature in degrees Celsius.
  final int temperature;

  /// Weather condition (e.g., sunny, rainy).
  final String condition;

  /// Human-readable weather summary.
  final String summary;

  /// Creates a new weather instance.
  const AddMealWeather({
    required this.temperature,
    required this.condition,
    required this.summary,
  });
}

/// Snapshot of user's dietary preferences.
/// Contains diet type, allergies, and disliked ingredients.
class AddMealPreferenceSnapshot {
  /// Diet type (e.g., vegetarian, keto, none).
  final String diet;

  /// List of food allergies.
  final List<String> allergies;

  /// List of disliked ingredients.
  final List<String> dislikes;

  /// Creates a new preference snapshot.
  const AddMealPreferenceSnapshot({
    required this.diet,
    required this.allergies,
    required this.dislikes,
  });

  /// Whether a diet preference has been set.
  bool get hasDiet => diet.trim().isNotEmpty;

  /// Whether there are any disliked ingredients.
  bool get hasDislikes => dislikes.isNotEmpty;
}

/// Represents a recipe generated by AI or from the database.
/// Contains complete recipe information including ingredients and nutrition.
class AddMealAiRecipe {
  /// Unique identifier of the recipe.
  final String id;

  /// Display title of the recipe.
  final String title;

  /// Duration label (e.g., "30 mins").
  final String durationLabel;

  /// Difficulty label (e.g., "Easy", "Intermediate").
  final String difficultyLabel;

  /// Serving size label (e.g., "4 servings").
  final String servingLabel;

  /// Path to the recipe's image asset.
  final String imagePath;

  /// Base64-encoded image data (optional).
  final String? imageBase64;

  /// Description of the recipe.
  final String description;

  /// Reasons why this recipe was recommended.
  final List<String> reasons;

  /// List of ingredients for the recipe.
  final List<AddMealAiIngredient> ingredients;

  /// Cooking instructions for the recipe.
  final List<String> instructions;

  /// Calorie count per serving.
  final int calories;

  /// Carbohydrates content in grams.
  final double carbohydrates;

  /// Fat content in grams.
  final double fat;

  /// Protein content in grams.
  final double protein;

  /// Prompt used to generate the image (if AI-generated).
  final String imagePrompt;

  /// Category name of the recipe.
  final String categoryName;

  /// Creates a new AI recipe instance.
  const AddMealAiRecipe({
    required this.id,
    required this.title,
    required this.durationLabel,
    required this.difficultyLabel,
    required this.servingLabel,
    required this.imagePath,
    this.imageBase64,
    required this.description,
    required this.reasons,
    this.ingredients = const [],
    this.instructions = const [],
    this.calories = 0,
    this.carbohydrates = 0,
    this.fat = 0,
    this.protein = 0,
    this.imagePrompt = '',
    this.categoryName = '',
  });
}

/// Represents an ingredient in an AI-generated recipe.
/// Contains name, amount, unit, and nutritional information.
class AddMealAiIngredient {
  /// Name of the ingredient.
  final String name;

  /// Amount of the ingredient.
  final double amount;

  /// Unit of measurement (e.g., "g", "ml", "cup").
  final String unit;

  /// Calories contributed by this ingredient.
  final double calories;

  /// Carbohydrates content in grams.
  final double carbohydrates;

  /// Fat content in grams.
  final double fat;

  /// Protein content in grams.
  final double protein;

  /// Practical replacement ingredients.
  final List<String> alternatives;

  /// Creates a new AI ingredient instance.
  const AddMealAiIngredient({
    required this.name,
    required this.amount,
    required this.unit,
    this.calories = 0,
    this.carbohydrates = 0,
    this.fat = 0,
    this.protein = 0,
    this.alternatives = const [],
  });
}

/// Represents a meal category option.
/// Contains an identifier and display name.
class AddMealCategoryOption {
  /// Unique identifier of the category.
  final String id;

  /// Display name of the category.
  final String name;

  /// Creates a new meal category option.
  const AddMealCategoryOption({required this.id, required this.name});
}
